openapi: 3.2.0
info:
  version: '25.02'
  title: Dispute API 3.0 Attachments API
  description: The following documents the Intake API and Interaction APIs.
  termsOfService: ''
  contact: {}
  license:
    name: ''
servers:
- url: '{corename}.gft-dispute-api.{env}.gpsrv.com/gft-dispute-api/1.0/'
tags:
- name: Attachments
paths:
  /claim/attachments/add:
    parameters:
    - $ref: '#/components/parameters/AuthorizationHeaderParam'
    - $ref: '#/components/parameters/ProfileTypeHeaderParam'
    post:
      summary: /claim/attachments/add
      operationId: postClaimAttachmentsAdd
      description: Use this endpoint to add attachments to an existing claim
      parameters: []
      responses:
        '200':
          description: Successful add attachments request
          content:
            application/json:
              schema:
                type: object
                properties:
                  StatusList:
                    type: array
                    items:
                      type: object
                      properties:
                        Type:
                          type: string
                          description: Status of the request
                          examples:
                          - Success
                          enum:
                          - Error
                          - Success
                        Message:
                          type: string
                          description: Message about the status
                          examples:
                          - Success
                        Code:
                          type: string
                          description: Numeric code for the status
                          examples:
                          - '200'
                  rtoken:
                    type: string
                    nullable: true
                    description: A system-generated ID used for tracking
                  StatusCode:
                    type: integer
                    nullable: true
                    description: The HTTP response status code
              examples:
                successExample:
                  value:
                    StatusList:
                    - Type: Success
                      Message: Success
                      Code: '200'
                    rtoken: 984513-395483653-4483483478
                    StatusCode: '200'
                  summary: A sample Success response
        '400':
          description: Error add attachment request
          content:
            application/json:
              schema:
                type: object
                properties:
                  StatusList:
                    type: array
                    items:
                      type: object
                      properties:
                        Type:
                          type: string
                          description: Status of the request
                          examples:
                          - Success
                          enum:
                          - Error
                          - Success
                        Message:
                          type: string
                          description: Message about the status
                          examples:
                          - Success
                        Code:
                          type: string
                          description: Numeric code for the status
                          examples:
                          - '200'
                  rtoken:
                    type: string
                    nullable: true
                    description: A system-generated ID used for tracking
                  StatusCode:
                    type: integer
                    nullable: true
                    description: The HTTP response status code
              examples:
                attachmentAddError:
                  value:
                    StatusList:
                    - Type: Error
                      Message: fail, Error adding the attachment
                    rtoken: 984513-395483653-4483483478
                    StatusCode: '400'
                  summary: A sample add attachment Error Response
                error4Example:
                  value:
                    StatusList:
                    - Type: Error
                      Message: The requested Claim ID is not valid.
                      Code: '4'
                    rtoken: 984513-395483653-4483483478
                    StatusCode: '400'
                  summary: A sample Error 4 response
                error5Example:
                  value:
                    StatusList:
                    - Type: Error
                      Message: 'Invalid Request: {message}'
                      Code: '5'
                    rtoken: 984513-395483653-4483483478
                    StatusCode: '400'
                  summary: A sample Error 5 response
                error14Example:
                  value:
                    StatusList:
                    - Type: Error
                      Message: Invalid request message
                      Code: '14'
                    rtoken: 984513-395483653-4483483478
                    StatusCode: '400'
                  summary: A sample Error 14 response
                error19Example:
                  value:
                    StatusList:
                    - Type: Error
                      Message: Unable to Process request. The ClaimID has not been submitted..
                      Code: '19'
                    rtoken: 984513-395483653-4483483478
                    StatusCode: '400'
                  summary: A sample Error 19 response
        '500':
          description: Error add attachments request
          content:
            application/json:
              schema:
                type: object
                properties:
                  StatusList:
                    type: array
                    items:
                      type: object
                      properties:
                        Type:
                          type: string
                          description: Status of the request
                          examples:
                          - Success
                          enum:
                          - Error
                          - Success
                        Message:
                          type: string
                          description: Message about the status
                          examples:
                          - Success
                        Code:
                          type: string
                          description: Numeric code for the status
                          examples:
                          - '200'
                  rtoken:
                    type: string
                    nullable: true
                    description: A system-generated ID used for tracking
                  StatusCode:
                    type: integer
                    nullable: true
                    description: The HTTP response status code
              examples:
                errorExample:
                  value:
                    StatusList:
                    - Type: Error
                      Message: Could not obtain a lock on the claim
                      Code: '500'
                    rtoken: 984513-395483653-4483483478
                    StatusCode: '500'
                  summary: A sample Error 500 response
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - ClaimId
              - AttachmentList
              - transactionId
              - providerId
              properties:
                providerId:
                  type: integer
                  format: int32
                  description: 'Your unique provider identifier from SoFi Tech Solutions.

                    Pattern: Max 10 digits

                    Example: `9999`'
                  example: 9999
                transactionId:
                  type: string
                  maxLength: 60
                  minLength: 1
                  description: 'Supply a globally unique ID to identify this endpoint request ("transaction").

                    Pattern: Max 60 characters

                    Example: `"984513-395483653-4483483478"`'
                  example: 984513-395483653-4483483478
                ClaimId:
                  type: string
                  description: Unique claim ID
                  example: 2108160022C
                AttachmentList:
                  type: array
                  description: List of attachments to add to the claim
                  items:
                    allOf:
                    - type: object
                      required:
                      - FileName
                      - Category
                      - Label
                      - DocumentStream
                      properties:
                        DocumentStream:
                          type: string
                          description: Byte stream of the form PDF being uploaded to satisfy the requirement
                          examples:
                          - JVBERi0xLjQKJcfl9OXwCjEgMCBvYmoKPDwKL0ZpbHRlciAvRmxhdGVEZWNvZGUKL0xlbmd0aCAxMjU4Cj4+CnN0cmVhbQp42s1YW3PTOBR+r+
                        Category:
                          type: string
                          description: Attachment category (one of the subset of `ValidAttachmentCategoryList` in the `/claim/documents/retrieveRequirements` response)
                          examples:
                          - SupportingDocumentation
                        FileName:
                          type: string
                          description: Name of the file being passed in DocumentStream param
                          examples:
                          - StatementOfDispute.pdf
                        Label:
                          type: string
                          description: User friendly attachment label
                          examples:
                          - Statement of Dispute
      tags:
      - Attachments
components:
  parameters:
    AuthorizationHeaderParam:
      name: Authorization
      in: header
      description: For `{token}` insert base64-encoded `apiLogin:apiTransKey`
      schema:
        type: string
        default: Basic {token}
    ProfileTypeHeaderParam:
      name: profile-type
      in: header
      description: Optional param to call Dispute API as a customer-service agent or a cardholder
      schema:
        type: string
        enum:
        - agent
        - cardholder
        default: agent
externalDocs:
  url: ''
  description: ''
x-readme:
  explorer-enabled: true
  proxy-enabled: true
